<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpTracker.DataAccess.PostgreSQL\ExpTracker.DataAccess.PostgreSQL.csproj" />
    <ProjectReference Include="..\ExpTracker.Entities\ExpTracker.Entities.csproj" />
  </ItemGroup>

</Project>
