openapi: "3.0.3"
info:
  title: Exp tracker
  version: "1.0"
servers:
  - url: http://localhost:5000
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Регистрация
      description: Регистрация нового пользователя
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthParameters"
      responses:
        "200":
          description: Успешная регистрация
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenPair"
        "400":
          description: Пользователь уже существует
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
  /auth/login:
    post:
      tags:
        - Auth
      summary: Вход
      description: Вход в профиль существующего пользователя
      operationId: logIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthParameters"
      responses:
        "200":
          description: Успешный вход в аккаунт
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenPair"
        "404":
          description: Пользователь с таким логином и паролем не существует
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
  /auth/refresh:
    post:
      tags:
        - Auth
      summary: Обновление пары токенов авторизации
      description: Обновление пары токенов авторизации
      operationId: refreshToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenRequest"
      responses:
        "200":
          description: Успешное обновление пары токенов авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenPair"
        "401":
          description: Некорректный формат токена или токен устарел/не соответствует текущему в БД
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
  /auth/logout:
    post:
      tags:
        - Auth
      summary: Выход
      description: Выход из учетной записи с отзывом refresh токена
      operationId: logOut
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenRequest"
      responses:
        "201":
          description: Успешный выход из учетной записи. Refresh токен отозван
          content: {}
        "403":
          description: Некорректный формат токена или токен устарел/не соответствует текущему в БД
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
  /targets:
    get:
      security:
        - bearerAuth: []
      tags:
        - Targets
      summary: Получить все накопительные цели пользователя
      operationId: listTargets
      responses:
        "200":
          description: Список накопительных целей пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Target"
        "400":
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "500":
          description: Техническая ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"

components:
  schemas:
    AuthParameters:
      type: object
      description: Параметры авторизации - пара логин и пароль
      properties:
        login:
          type: string
          maxLength: 10
          minLength: 3
          description: Логин пользователя
          example: user123
        password:
          type: string
          description: Пароль пользователя
          minLength: 8
      required:
        - login
        - password
    Target:
      type: object
      description: Накопительная цель пользователя
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Идентификатор накопительной цели пользователя
          example: 1
        userId:
          type: integer
          format: int64
          readOnly: true
          description: Идентификатор пользователя, которому принадлежит данная цель
        name:
          type: string
          minLength: 3
          maxLength: 100
          description: Название накопительной цели пользователя
          example: Автомобиль
        description:
          type: string
          maxLength: 2048
          description: Описание накопительной цели пользователя
          example: Нужна машина для пассажирских перевозок
        created:
          type: string
          format: date-time
          description: Дата и время создания накопительной цели в UTC
          example: "2025-07-15T17:07:00Z"
        endTime:
          type: string
          format: date-time
          description: Дата окончания накопительной цели
          example: "2026-11-30T00:00:00Z"
        targetCost:
          type: integer
          format: int64
          description: Целевая сумма, которую необходимо накопить
          example: 80000000
        currentAmount:
          type: integer
          format: int64
          description: Сумма, отложенная на данный момент
          example: 12000000
      required:
        - id
        - userId
        - name
        - created
        - endTime
        - targetCost
        - currentAmount
    RefreshTokenRequest:
      type: object
      description: Запрос обновления пары токенов авторизации
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken
    TokenPair:
      type: object
      description: Пара JWT токенов авторизации
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - accessToken
        - refreshToken
    ErrorSchema:
      type: object
      properties:
        code:
          description: HTTP код ошибки
          enum:
            - 400
            - 401
            - 403
            - 404
            - 500
        message:
          type: string
      required:
        - code
        - message
  responses:
    Error400:
      description: Ошибка. Неправильные данные запроса
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"
    Error404:
      description: Ошибка. Ресурс не найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
