<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
      <Folder Include="Middlewares\" />
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ExpTracker.Core\ExpTracker.Core.csproj" />
      <ProjectReference Include="..\ExpTracker.DataAccess\ExpTracker.DataAccess.csproj" />
      <ProjectReference Include="..\ExpTracker.Entities\ExpTracker.Entities.csproj" />
    </ItemGroup>

</Project>
